services:
  - type: web
    name: surf-tg
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      # Startup Config
      - key: API_ID
        value: "28402967"
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: AUTH_CHANNEL
        value: "-1003533429498"
      - key: DATABASE_URL
        sync: false
      - key: SESSION_STRING
        sync: false
      
      # Additional CDN Bots
      - key: MULTI_TOKEN1
        sync: false
      - key: MULTI_TOKEN2
        sync: false
      - key: MULTI_TOKEN3
        sync: false
      - key: MULTI_TOKEN4
        sync: false
      - key: MULTI_TOKEN5
        sync: false
      - key: MULTI_TOKEN6
        sync: false
      - key: MULTI_TOKEN7
        sync: false
      - key: MULTI_TOKEN8
        sync: false
      
      # Web Config
      - key: BASE_URL
        fromService:
          type: web
          name: surf-tg
          property: host
      - key: PORT
        value: "8080"
      
      # Login Details
      - key: USERNAME
        value: "admin"
      - key: PASSWORD
        sync: false
      
      # Playlist Login Details
      - key: ADMIN_USERNAME
        value: "surfTG"
      - key: ADMIN_PASSWORD
        sync: false
      
      # Performance Config
      - key: SLEEP_THRESHOLD
        value: "60"
      - key: WORKERS
        value: "100"
      - key: MULTI_CLIENT
        value: "True"
      - key: HIDE_CHANNEL
        value: ""
      - key: CACHE_MAX_SIZE_GB
        value: "120"
